from requests import get
class Client():
	def __init__(self):
		self.api="https://random.onl/json"
		self.headers = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36","x-requested-with": "XMLHttpRequest"}
	def name_list(self):
                return get(f"{self.api}/name.json",headers=self.headers).json()
	def animals_list(self):
                return get(f"{self.api}/animals.json",headers=self.headers).json()
	def drawing_list(self):
                return get(f"{self.api}/drawing.json",headers=self.headers).json()
	def country_list(self):
                return get(f"{self.api}/country.json",headers=self.headers).json()
	def state_list(self):
                return get(f"{self.api}/state.json",headers=self.headers).json()
	def cities_list(self):
                return get(f"{self.api}/cities.json",headers=self.headers).json()
	def comic_list(self):
                return get(f"{self.api}/comic.json",headers=self.headers).json()
	def outfits_list(self):
                return get(f"{self.api}/outfits.json",headers=self.headers).json()
	def card_list(self):
                return get(f"{self.api}/card.json",headers=self.headers).json()
	def superhero_list(self):
                return get(f"{self.api}/superhero.json",headers=self.headers).json()
	def actor_list(self):
                return get(f"{self.api}/actor.json",headers=self.headers).json()
	def memes_list(self):
                return get(f"{self.api}/memes.json",headers=self.headers).json()
	def flag_list(self):
                return get(f"{self.api}/flag.json",headers=self.headers).json()
	def car_list(self):
                return get(f"{self.api}/car.json",headers=self.headers).json()
	def quirk_list(self):
                return get(f"{self.api}/quirk.json",headers=self.headers).json()
	def birds_list(self):
                return get(f"{self.api}/birds.json",headers=self.headers).json()
	def food_list(self):
                return get(f"{self.api}/food.json",headers=self.headers).json()
	def recipes_list(self):
                return get(f"{self.api}/recipes.json",headers=self.headers).json()
	def nbateam_list(self):
                return get(f"{self.api}/nbateam.json",headers=self.headers).json()
	def title_list(self):
                return get(f"{self.api}/title.json",headers=self.headers).json()
	def mlb_list(self):
                return get(f"{self.api}/mlb.json",headers=self.headers).json()
	def nbaplayer_list(self):
                return get(f"{self.api}/nbaplayer.json",headers=self.headers).json()
	def songs_list(self):
                return get(f"{self.api}/songs.json",headers=self.headers).json()
	def emoji_list(self):
                return get(f"{self.api}/emoji.json",headers=self.headers).json()
	def pictures_list(self):
                return get(f"{self.api}/pictures.json",headers=self.headers).json()
	def celebrity_list(self):
                return get(f"{self.api}/celebrity.json",headers=self.headers).json()
	def monster_list(self):
                return get(f"{self.api}/monster.json",headers=self.headers).json()
	def games_list(self):
                return get(f"{self.api}/games.json",headers=self.headers).json()
	def superpower_list(self):
                return get(f"{self.api}/superpower.json",headers=self.headers).json()
	def anime_list(self):
                return get(f"{self.api}/anime.json",headers=self.headers).json()
	def question_list(self):
                return get(f"{self.api}/question.json",headers=self.headers).json()
	def facts_list(self):
                return get(f"{self.api}/facts.json",headers=self.headers).json()
	def college_list(self):
                return get(f"{self.api}/college.json",headers=self.headers).json()
	def teamname_list(self):
                return get(f"{self.api}/teamname1.json",headers=self.headers).json()
	def last_name_list(self):
                return get(f"{self.api}/last-name.json",headers=self.headers).json()
	def phone_number_list(self):
                return get(f"{self.api}/phone-number.json",headers=self.headers).json()
	def phrase_list(self):
                return get(f"{self.api}/phrase.json",headers=self.headers).json()
	def sentence_list(self):
                return get(f"{self.api}/sentence.json",headers=self.headers).json()
	def zipcode_list(self):
                return get(f"{self.api}/zipcode.json",headers=self.headers).json()
	def zipcodes_list(self):
                return get(f"{self.api}/zip-codes.json",headers=self.headers).json()
	def place_list(self):
                return get(f"{self.api}/place.json",headers=self.headers).json()
	def town_list(self):
                return get(f"{self.api}/town.json",headers=self.headers).json()
	def coordinates_list(self):
                return get(f"{self.api}/coordinates.json",headers=self.headers).json()
	def street_list(self):
                return get(f"{self.api}/street.json",headers=self.headers).json()
	def job_list(self):
                return get(f"{self.api}/job.json",headers=self.headers).json()
	def object_list(self):
                return get(f"{self.api}/object.json",headers=self.headers).json()
	def fruits_list(self):
                return get(f"{self.api}/fruits.json",headers=self.headers).json()
	def weapon_list(self):
                return get(f"{self.api}/weapon.json",headers=self.headers).json()